en:
  languageName: English
  weight: 1
  title: "Pelican Bay Tennis Groups"
  params:
    description: "Infomation about Pelican Bay Tennis Groups"
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1