######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/assets/logo.svg"
logo_on_black: "/assets/logo.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/assets/logo.png"]

github:
  repo_url: "https://github.com/pelicanbaytennisgroups/www/blob/main"
  show_edit_link: false

social_links:
  facebook: ""
  instagram: ""
  linkedin: ""
  email: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false

# Site info
site_info:
  title: "Pelican Bay Tennis Groups"
  description: "Monthly tennis pairings and schedules for Pelican Bay Tennis Groups"
  footer_text: "© Pelican Bay Tennis Groups. All rights reserved."
