baseURL = 'https://pelicanbaytennisgroups.com/'
languageCode = 'en-us'
title = 'Pelican Bay Tennis Groups'
theme = ["hugo-embed-pdf-shortcode", "mini"]
enableInlineShortcodes = true

[module]
  [[module.mounts]]
    source = "content/pages"
    target = "static"